name: Keep Render Alive

on:
  schedule:
    - cron: "*/30 * * * 1-6" # every 30 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping every 30mins
        run: curl -s https://four44-ecommerce.onrender.com > /dev/null
